-- ESTE ES EL QUE VA A CONTROLAR LOS DATOS


--EJECUTAR DESDE SYSTEM
-- CREAR TABLESPACES Y DATAFILES
CREATE TABLESPACE "TSTALLER1" DATAFILE 'C:\app\Chiefpc\product\21c\oradata\XE\TSTALLER1.DBF' SIZE 1000M;
CREATE TEMPORARY TABLESPACE "TSTALLER1_TEMP" TEMPFILE 'C:\app\Chiefpc\product\21c\oradata\XE\TSTALLER1_TEMP.DBF' SIZE 1000M;

--CREAR USUARIO
CREATE USER TALLER1 IDENTIFIED BY 1234 DEFAULT TABLESPACE TSTALLER1 TEMPORARY TABLESPACE TSTALLER1_TEMP;

--DAR PERMISOS A USUARIO ADMIN SOBRE TABLESPACES
GRANT UNLIMITED TABLESPACE TO TALLER1;

--DAR ROL ADMIN A USUARIO
GRANT CONNECT, RESOURCE, DBA TO TALLER1;


REVOKE ALL PRIVILEGES FROM TALLER1;
DROP USER TALLER2 CASCADE;
