/************************************************************************************
Descripción: Tabla encargada de almacenar la información sobre
			 todas las viviendas registradas
Autor:       Manuel Alejandro Gallego Jiménez
Fecha:       12-10-2023 (DD/MM/AA)
IdGestión:   
@copyright: 
************************************************************************************/

CREATE TABLE APP_PAGO_PREDIAL.PGP_PROPERTY
(
ID_POPERTY						INTEGER,
CITY							VARCHAR2(20)	NOT NULL, 
ADDRESS							VARCHAR2(30)	NOT NULL,
STRATUM							VARCHAR2(1) 	NOT NULL,
REQUEST_DATE					DATE			NOT NULL,
TAX								INTEGER			NOT NULL,
PROPERTY_TYPE					VARCHAR2(14)	NOT NULL,
DOCUMENT						VARCHAR2(15) 	NOT NULL,
CONSTRAINT PK_PROPTY PRIMARY KEY(ID_POPERTY),
CONSTRAINT CK_PROPTY_STRATUM_01 CHECK (STRATUM >= 1 AND STRATUM <= 6),
CONSTRAINT CK_PROPTY_TAX_02 CHECK (TAX > 1 AND TAX <= 10000000),
CONSTRAINT CK_PROPTY_PROPERTY_TYPE_03 CHECK (PROPERTY_TYPE IN ('Residencial', 'No residencial')),
CONSTRAINT FK_PROPTY_DOCMNT_01 FOREIGN KEY(DOCUMENT) REFERENCES APP_PAGO_PREDIAL.PGP_OWNER(DOCUMENT)
)

/

COMMENT ON TABLE APP_PAGO_PREDIAL.PGP_PROPERTY IS 'Information about all the properties registered';
COMMENT ON COLUMN APP_PAGO_PREDIAL.PGP_PROPERTY.ID_POPERTY IS 'Id autogenerated of the property';
COMMENT ON COLUMN APP_PAGO_PREDIAL.PGP_PROPERTY.CITY IS 'City where the property is';
COMMENT ON COLUMN APP_PAGO_PREDIAL.PGP_PROPERTY.ADDRESS IS 'Address of the property';
COMMENT ON COLUMN APP_PAGO_PREDIAL.PGP_PROPERTY.STRATUM IS 'Strarum of the property';
COMMENT ON COLUMN APP_PAGO_PREDIAL.PGP_PROPERTY.REQUEST_DATE IS 'Date when the property was registered on the database';
COMMENT ON COLUMN APP_PAGO_PREDIAL.PGP_PROPERTY.TAX IS 'Tax that has to be paid';
COMMENT ON COLUMN APP_PAGO_PREDIAL.PGP_PROPERTY.PROPERTY_TYPE IS 'Type of the property, it can be Residencial or No residencial';
COMMENT ON COLUMN APP_PAGO_PREDIAL.PGP_PROPERTY.DOCUMENT IS 'Foreign key that refrences documento on the table OWNER';

/
