-- ESTE ES EL QUE VA A CONTROLAR LOS DATOS


--EJECUTAR DESDE SYSTEM
-- CREAR TABLESPACES Y DATAFILES
CREATE TABLESPACE "TSAPP_PAGO_PREDIAL" DATAFILE 'C:\app\Chiefpc\product\21c\oradata\XE\TSAPP_PAGO_PREDIAL.DBF' SIZE 2048M;
CREATE TEMPORARY TABLESPACE "TSAPP_PAGO_PREDIAL_TEMP" TEMPFILE 'C:\app\Chiefpc\product\21c\oradata\XE\TSAPP_PAGO_PREDIAL_TEMP.DBF' SIZE 1024M;

--CREAR USUARIO/ESQUEMA
CREATE USER APP_PAGO_PREDIAL IDENTIFIED BY 1234 DEFAULT TABLESPACE TSAPP_PAGO_PREDIAL TEMPORARY TABLESPACE TSAPP_PAGO_PREDIAL_TEMP;

GRANT UNLIMITED TABLESPACE TO APP_PAGO_PREDIAL;
GRANT CREATE SESSION TO APP_PAGO_PREDIAL;
GRANT CREATE TABLE TO APP_PAGO_PREDIAL;
--GRANT INSERT, UPDATE, DELETE ON SCHEMA_NAME.TABLE_NAME TO APP_PAGO_PREDIAL;
--GRANT CREATE INDEX TO APP_PAGO_PREDIAL;
GRANT CREATE PROCEDURE TO APP_PAGO_PREDIAL;
GRANT EXECUTE ON APP_PAGO_PREDIAL.PKG_DISCOUNT_REGISTRATION TO APP_PAGO_PREDIAL;

GRANT CREATE JOB TO APP_PAGO_PREDIAL;

--DAR PERMISOS A USUARIO ADMIN SOBRE TABLESPACES
--GRANT UNLIMITED TABLESPACE TO TSAPP_PAGO_PREDIAL;
--DAR ROL ADMIN A USUARIO
--GRANT CONNECT, RESOURCE, DBA TO TSAPP_PAGO_PREDIAL;
--SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'SYSTEM';
