DROP PACKAGE PKG_DISCOUNT_REGISTRATION;

-- Valores descuento especial
INSERT INTO APP_PAGO_PREDIAL.PGP_SPECIAL_DISCOUNT (ID_SPECIAL_DISCOUNT, SPECIAL_DISCOUNT)
VALUES (1, 5);

INSERT INTO APP_PAGO_PREDIAL.PGP_SPECIAL_DISCOUNT (ID_SPECIAL_DISCOUNT, SPECIAL_DISCOUNT)
VALUES (2, 0);

-- Descuento de estrato
INSERT INTO APP_PAGO_PREDIAL.PGP_STRATA_DISCOUNT (ID_STRATUM_DISCOUNT, STRATUM_DISCOUNT)
VALUES (1, 20);

INSERT INTO APP_PAGO_PREDIAL.PGP_STRATA_DISCOUNT (ID_STRATUM_DISCOUNT, STRATUM_DISCOUNT)
VALUES (2, 30);

INSERT INTO APP_PAGO_PREDIAL.PGP_STRATA_DISCOUNT (ID_STRATUM_DISCOUNT, STRATUM_DISCOUNT)
VALUES (3, 40);

-- Propietarios prueba
INSERT INTO APP_PAGO_PREDIAL.PGP_OWNER (DOCUMENT, DOCUMENT_TYPE, FIRST_NAME, LAST_NAME, OVER_60, HEAD_OF_HOUSEHOLD, UNENPLOYED)
VALUES ('12345', 'CC', 'Juan', 'Pérez', 'Si', 'Si', 'No');

INSERT INTO APP_PAGO_PREDIAL.PGP_OWNER (DOCUMENT, DOCUMENT_TYPE, FIRST_NAME, LAST_NAME, OVER_60, HEAD_OF_HOUSEHOLD, UNENPLOYED)
VALUES ('67890', 'TI', 'María', 'Gómez', 'No', 'No', 'Si');

-- Datos en la tabla PGP_PROPERTY relacionados con los propietarios anteriores

INSERT INTO APP_PAGO_PREDIAL.PGP_PROPERTY (ID_PROPERTY, CITY, ADDRESS, STRATUM, REQUEST_DATE, TAX, PROPERTY_TYPE, DOCUMENT)
VALUES (1, 'Ciudad 1', 'Dirección 1', '4', TO_DATE('2023-10-15', 'YYYY-MM-DD'), 2000, 'Residencial', '12345');

INSERT INTO APP_PAGO_PREDIAL.PGP_PROPERTY (ID_PROPERTY, CITY, ADDRESS, STRATUM, REQUEST_DATE, TAX, PROPERTY_TYPE, DOCUMENT)
VALUES (2, 'Ciudad 2', 'Dirección 2', '3', TO_DATE('2023-09-20', 'YYYY-MM-DD'), 1500, 'No residencial', '67890');

-- Insertar un dato en PGP_DISCOUNT_REGISTRATION
INSERT INTO APP_PAGO_PREDIAL.PGP_DISCOUNT_REGISTRATION (ID_DISCOUNT_REGISTRATION, NET_PAYMENT, DEADLINE_DATE, STATUS, ID_PROPERTY, DOCUMENT, ID_STRATUM_DISCOUNT, ID_SPECIAL_DISCOUNT)
VALUES (1, 2500, TO_DATE('2023-12-31', 'YYYY-MM-DD'), 'Sin pagar', 1, '12345', 2, 1);

INSERT INTO APP_PAGO_PREDIAL.PGP_DISCOUNT_REGISTRATION (ID_DISCOUNT_REGISTRATION, NET_PAYMENT, DEADLINE_DATE, STATUS, ID_PROPERTY, DOCUMENT, ID_STRATUM_DISCOUNT, ID_SPECIAL_DISCOUNT)
VALUES (2, 1800, TO_DATE('2023-11-15', 'YYYY-MM-DD'), 'Sin pagar', 2, '67890', 2, 1);


BEGIN
  PKG_DISCOUNT_REGISTRATION.UpdateStatus(1);
END;

BEGIN
  PKG_DISCOUNT_REGISTRATION.CheckAndUpdateStatus;
END;