/************************************************************************************
Descripción: Esquema de la base de datos
Autor:       Manuel Alejandro Gallego Jiménez
Fecha:       12-08-2023 (DD/MM/AA)
IdGestión:   
@copyright: 
************************************************************************************/

-- ESTE ES EL QUE VA A CONTROLAR LOS DATOS
-- EJECUTAR DESDE SYSTEM
-- CREAR TABLESPACES Y DATAFILES
CREATE TABLESPACE "TSAPP_PAGO_PREDIAL" 
	DATAFILE 'C:\app\Chiefpc\product\21c\oradata\XE\TSAPP_PAGO_PREDIAL.DBF' 
	SIZE 1024M;
CREATE TEMPORARY TABLESPACE "TSAPP_PAGO_PREDIAL_TEMP" 
	TEMPFILE 'C:\app\Chiefpc\product\21c\oradata\XE\TSAPP_PAGO_PREDIAL_TEMP.DBF' 
	SIZE 512M;

--CREAR USUARIO/ESQUEMA
CREATE USER APP_PAGO_PREDIAL IDENTIFIED BY 1234
DEFAULT TABLESPACE TSAPP_PAGO_PREDIAL 
TEMPORARY TABLESPACE TSAPP_PAGO_PREDIAL_TEMP;

GRANT UNLIMITED TABLESPACE TO APP_PAGO_PREDIAL;
GRANT CREATE SESSION TO APP_PAGO_PREDIAL;
GRANT CREATE TABLE TO APP_PAGO_PREDIAL;
GRANT CREATE PROCEDURE TO APP_PAGO_PREDIAL;
GRANT EXECUTE ON APP_PAGO_PREDIAL.PKG_DISCOUNT_REGISTRATION TO APP_PAGO_PREDIAL;
GRANT CREATE SEQUENCE TO APP_PAGO_PREDIAL;
GRANT CREATE JOB TO APP_PAGO_PREDIAL;